import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("IMDB Dataset.csv")
df.columns = df.columns.str.strip()
df['Runtime'] = df['Runtime'].str.replace(' min', '', regex=False)
df['Runtime'] = pd.to_numeric(df['Runtime'], errors='coerce')
print("First 3 Rows:")
print(df.head(3))
print("\nLast 3 Rows:")
print(df.tail(3))
print("\nDataset Information:")
df.info()
print("\nNull Values:")
print(df.isnull().sum())
print("\nRows 41 to 75:")
print(df.iloc[40:75])
print("\nMovie with Highest Votes:")
print(df[df['Votes'] == df['Votes'].max()])
df[['IMDB_Rating', 'Runtime']].boxplot(figsize=(8,5))
plt.title("Boxplot of IMDB Rating and Runtime")
plt.show()
plt.scatter(df['Runtime'], df['IMDB_Rating'])
plt.xlabel("Runtime")
plt.ylabel("IMDB Rating")
plt.title("Runtime vs IMDB Rating")
plt.show()
df[['IMDB_Rating', 'Runtime']].hist(figsize=(10,5))
plt.show()
plt.figure(figsize=(12,6))
sns.countplot(x='IMDB_Rating', data=df)
plt.xticks(rotation=90)
plt.show()